spring.application.name=SmartRent

# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:smartrentdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=visitor
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console - so you can see your tables in the browser
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


# MySQL Database Configuration
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL:mysql://localhost:3306/smart_rent_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Chukwunyerem457}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Show SQL in the console (helpful for debugging your queries)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Redis Connection
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Tell Spring to use Redis as the cache manager
spring.cache.type=redis

#Security Secrets
jwt.secrets = ${JWT_SECRET}


#PAYSTACK
paystack.secret.key=${PAY_STACK_SECRET}



